/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServiceAreasRouteImport } from './routes/service-areas'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesWholeHomeRemodelingRouteImport } from './routes/services/whole-home-remodeling'
import { Route as ServicesVeterinaryHospitalConstructionRouteImport } from './routes/services/veterinary-hospital-construction'
import { Route as ServicesVeterinaryClinicRenovationRouteImport } from './routes/services/veterinary-clinic-renovation'
import { Route as ServicesKitchenRemodelingRouteImport } from './routes/services/kitchen-remodeling'
import { Route as ServicesHomeAdditionsRouteImport } from './routes/services/home-additions'
import { Route as ServicesBathroomRemodelingRouteImport } from './routes/services/bathroom-remodeling'
import { Route as ServicesBasementRemodelingRouteImport } from './routes/services/basement-remodeling'
import { Route as ServicesAnimalHospitalBuildoutRouteImport } from './routes/services/animal-hospital-buildout'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAreasRoute = ServiceAreasRouteImport.update({
  id: '/service-areas',
  path: '/service-areas',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesWholeHomeRemodelingRoute =
  ServicesWholeHomeRemodelingRouteImport.update({
    id: '/services/whole-home-remodeling',
    path: '/services/whole-home-remodeling',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesVeterinaryHospitalConstructionRoute =
  ServicesVeterinaryHospitalConstructionRouteImport.update({
    id: '/services/veterinary-hospital-construction',
    path: '/services/veterinary-hospital-construction',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesVeterinaryClinicRenovationRoute =
  ServicesVeterinaryClinicRenovationRouteImport.update({
    id: '/services/veterinary-clinic-renovation',
    path: '/services/veterinary-clinic-renovation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesKitchenRemodelingRoute =
  ServicesKitchenRemodelingRouteImport.update({
    id: '/services/kitchen-remodeling',
    path: '/services/kitchen-remodeling',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesHomeAdditionsRoute = ServicesHomeAdditionsRouteImport.update({
  id: '/services/home-additions',
  path: '/services/home-additions',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesBathroomRemodelingRoute =
  ServicesBathroomRemodelingRouteImport.update({
    id: '/services/bathroom-remodeling',
    path: '/services/bathroom-remodeling',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesBasementRemodelingRoute =
  ServicesBasementRemodelingRouteImport.update({
    id: '/services/basement-remodeling',
    path: '/services/basement-remodeling',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesAnimalHospitalBuildoutRoute =
  ServicesAnimalHospitalBuildoutRouteImport.update({
    id: '/services/animal-hospital-buildout',
    path: '/services/animal-hospital-buildout',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRoute
  '/service-areas': typeof ServiceAreasRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/services/animal-hospital-buildout': typeof ServicesAnimalHospitalBuildoutRoute
  '/services/basement-remodeling': typeof ServicesBasementRemodelingRoute
  '/services/bathroom-remodeling': typeof ServicesBathroomRemodelingRoute
  '/services/home-additions': typeof ServicesHomeAdditionsRoute
  '/services/kitchen-remodeling': typeof ServicesKitchenRemodelingRoute
  '/services/veterinary-clinic-renovation': typeof ServicesVeterinaryClinicRenovationRoute
  '/services/veterinary-hospital-construction': typeof ServicesVeterinaryHospitalConstructionRoute
  '/services/whole-home-remodeling': typeof ServicesWholeHomeRemodelingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRoute
  '/service-areas': typeof ServiceAreasRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/services/animal-hospital-buildout': typeof ServicesAnimalHospitalBuildoutRoute
  '/services/basement-remodeling': typeof ServicesBasementRemodelingRoute
  '/services/bathroom-remodeling': typeof ServicesBathroomRemodelingRoute
  '/services/home-additions': typeof ServicesHomeAdditionsRoute
  '/services/kitchen-remodeling': typeof ServicesKitchenRemodelingRoute
  '/services/veterinary-clinic-renovation': typeof ServicesVeterinaryClinicRenovationRoute
  '/services/veterinary-hospital-construction': typeof ServicesVeterinaryHospitalConstructionRoute
  '/services/whole-home-remodeling': typeof ServicesWholeHomeRemodelingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRoute
  '/service-areas': typeof ServiceAreasRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/services/animal-hospital-buildout': typeof ServicesAnimalHospitalBuildoutRoute
  '/services/basement-remodeling': typeof ServicesBasementRemodelingRoute
  '/services/bathroom-remodeling': typeof ServicesBathroomRemodelingRoute
  '/services/home-additions': typeof ServicesHomeAdditionsRoute
  '/services/kitchen-remodeling': typeof ServicesKitchenRemodelingRoute
  '/services/veterinary-clinic-renovation': typeof ServicesVeterinaryClinicRenovationRoute
  '/services/veterinary-hospital-construction': typeof ServicesVeterinaryHospitalConstructionRoute
  '/services/whole-home-remodeling': typeof ServicesWholeHomeRemodelingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/projects'
    | '/service-areas'
    | '/sitemap.xml'
    | '/services/animal-hospital-buildout'
    | '/services/basement-remodeling'
    | '/services/bathroom-remodeling'
    | '/services/home-additions'
    | '/services/kitchen-remodeling'
    | '/services/veterinary-clinic-renovation'
    | '/services/veterinary-hospital-construction'
    | '/services/whole-home-remodeling'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/projects'
    | '/service-areas'
    | '/sitemap.xml'
    | '/services/animal-hospital-buildout'
    | '/services/basement-remodeling'
    | '/services/bathroom-remodeling'
    | '/services/home-additions'
    | '/services/kitchen-remodeling'
    | '/services/veterinary-clinic-renovation'
    | '/services/veterinary-hospital-construction'
    | '/services/whole-home-remodeling'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/projects'
    | '/service-areas'
    | '/sitemap.xml'
    | '/services/animal-hospital-buildout'
    | '/services/basement-remodeling'
    | '/services/bathroom-remodeling'
    | '/services/home-additions'
    | '/services/kitchen-remodeling'
    | '/services/veterinary-clinic-renovation'
    | '/services/veterinary-hospital-construction'
    | '/services/whole-home-remodeling'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ProjectsRoute: typeof ProjectsRoute
  ServiceAreasRoute: typeof ServiceAreasRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ServicesAnimalHospitalBuildoutRoute: typeof ServicesAnimalHospitalBuildoutRoute
  ServicesBasementRemodelingRoute: typeof ServicesBasementRemodelingRoute
  ServicesBathroomRemodelingRoute: typeof ServicesBathroomRemodelingRoute
  ServicesHomeAdditionsRoute: typeof ServicesHomeAdditionsRoute
  ServicesKitchenRemodelingRoute: typeof ServicesKitchenRemodelingRoute
  ServicesVeterinaryClinicRenovationRoute: typeof ServicesVeterinaryClinicRenovationRoute
  ServicesVeterinaryHospitalConstructionRoute: typeof ServicesVeterinaryHospitalConstructionRoute
  ServicesWholeHomeRemodelingRoute: typeof ServicesWholeHomeRemodelingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-areas': {
      id: '/service-areas'
      path: '/service-areas'
      fullPath: '/service-areas'
      preLoaderRoute: typeof ServiceAreasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/whole-home-remodeling': {
      id: '/services/whole-home-remodeling'
      path: '/services/whole-home-remodeling'
      fullPath: '/services/whole-home-remodeling'
      preLoaderRoute: typeof ServicesWholeHomeRemodelingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/veterinary-hospital-construction': {
      id: '/services/veterinary-hospital-construction'
      path: '/services/veterinary-hospital-construction'
      fullPath: '/services/veterinary-hospital-construction'
      preLoaderRoute: typeof ServicesVeterinaryHospitalConstructionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/veterinary-clinic-renovation': {
      id: '/services/veterinary-clinic-renovation'
      path: '/services/veterinary-clinic-renovation'
      fullPath: '/services/veterinary-clinic-renovation'
      preLoaderRoute: typeof ServicesVeterinaryClinicRenovationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/kitchen-remodeling': {
      id: '/services/kitchen-remodeling'
      path: '/services/kitchen-remodeling'
      fullPath: '/services/kitchen-remodeling'
      preLoaderRoute: typeof ServicesKitchenRemodelingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/home-additions': {
      id: '/services/home-additions'
      path: '/services/home-additions'
      fullPath: '/services/home-additions'
      preLoaderRoute: typeof ServicesHomeAdditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/bathroom-remodeling': {
      id: '/services/bathroom-remodeling'
      path: '/services/bathroom-remodeling'
      fullPath: '/services/bathroom-remodeling'
      preLoaderRoute: typeof ServicesBathroomRemodelingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/basement-remodeling': {
      id: '/services/basement-remodeling'
      path: '/services/basement-remodeling'
      fullPath: '/services/basement-remodeling'
      preLoaderRoute: typeof ServicesBasementRemodelingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/animal-hospital-buildout': {
      id: '/services/animal-hospital-buildout'
      path: '/services/animal-hospital-buildout'
      fullPath: '/services/animal-hospital-buildout'
      preLoaderRoute: typeof ServicesAnimalHospitalBuildoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ProjectsRoute: ProjectsRoute,
  ServiceAreasRoute: ServiceAreasRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ServicesAnimalHospitalBuildoutRoute: ServicesAnimalHospitalBuildoutRoute,
  ServicesBasementRemodelingRoute: ServicesBasementRemodelingRoute,
  ServicesBathroomRemodelingRoute: ServicesBathroomRemodelingRoute,
  ServicesHomeAdditionsRoute: ServicesHomeAdditionsRoute,
  ServicesKitchenRemodelingRoute: ServicesKitchenRemodelingRoute,
  ServicesVeterinaryClinicRenovationRoute:
    ServicesVeterinaryClinicRenovationRoute,
  ServicesVeterinaryHospitalConstructionRoute:
    ServicesVeterinaryHospitalConstructionRoute,
  ServicesWholeHomeRemodelingRoute: ServicesWholeHomeRemodelingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
